### ISSUE TITLE
Upgrade ojdbc jar versions in oracledb.driver

### ISSUE THREAD

**Issue by niveathika** [ballerina-platform/module-ballerinax-oracledb.driver#6]
**Description:**
$subject

With stable releases of Oracle19c, the supported driver versions are both ojdbc8 and ojdbc10. 

However xaTransaction feature is only supported in ojdbc10:19.16.0.0

**Comment by anupama-pathirage** [comment]
This is in PR sent column of https://github.com/ballerina-platform/ballerina-standard-library/projects/140. Why the PR is not tagged? @niveathika

**Comment by niveathika** [comment]
@anupama-pathirage Seems I have missed to link the issue. Done now. 

I will close the issue once the module is released to central.

**Comment by niveathika** [comment]
The driver is released to central, https://central.ballerina.io/ballerinax/oracledb.driver/1.1.0
